task: seg

data:
  name: kitti360_seg
  root_seg: /home/rk010/Desktop/Research/NurIPS/KITTI-360
  img_size: [192, 640]
  camera: image_00
  batch_size: 128
  num_workers: 4

train:
  epochs: 40
  depth: 10.0
  lr: 2.0e-3
  weight_decay: 1.0e-4
  sensor_lr_mult: 1.0
  ckpt_dir: ./checkpoints/nosensor_ablation
  log_interval: 100
  resume: true
  resume_path: ""
  load_strict: true
  keep_last_n: 3
  amp: true
  accum_steps: 1
  use_lovasz: true
  ohem_pct: 0.25
  smooth_lambda: 0.05

lens:
  path: /home/rk010/Desktop/Research/NurIPS/DeepLens/lenses/cellphone/cellphone80deg.json
  spp: 1
  render_scale: 0.75
  no_grad: true
  use_amp: true
  normalize_output: true
  target_mean: 0.5

sensor:
  cfa_init: bayer_rggb
  sensor_pitch: 2.0e-6
  bit_depth: 8
  read_noise_std: 0.003
  shot_noise_scale: 0.02

eval:
  viz_every: 50
  train_viz_steps: [1]
  include_stages_in_viz: true
  use_crf: false

debug:
  dump_stats: false
  bypass_cfa: true
  bypass_noise: true

model:
  width: 32
  num_classes: 19
  ignore_index: 255