name: kitti360_seg_modern_lraspp_efficientnet_b0_full
seed: 0
task: seg

data:
  name: kitti360_seg
  root_seg: /home/re141872/Research/data/kitti360
  img_size: [192, 640]
  camera: image_00
  label_encoding: original_id
  batch_size: 8
  num_workers: 4
  train_stride: 1
  val_stride: 1

pipeline:
  input: rgb

model:
  name: lraspp_efficientnet_b0
  num_classes: 19
  ignore_index: 255
  pretrained_backbone: true
  timm_model: efficientnet_b0

train:
  epochs: 80
  depth: 10.0
  lr: 0.0003
  weight_decay: 0.0001
  ckpt_dir: ./runs/modern_backbones/lraspp_efficientnet_b0_full
  log_interval: 100
  resume: false
  amp: true
  accum_steps: 1
  channels_last: false
  torch_compile: false
  keep_last_n: 3
  sensor_lr_mult: 0.0

debug:
  bypass_optics: true
  bypass_cfa: true
  bypass_noise: true

eval:
  viz_every: 200
  train_viz_steps: [1]
  include_stages_in_viz: true
  use_crf: false
