"""
Compose publication-quality qualitative figures from existing strip PNGs.

Each strip PNG (generated by generate_qualitative.py) contains 6 side-by-side panels:
  [Input RGB] [Ground Truth] [Fixed Camera] [No Optics (Tile-2)] [Tile-3] [Tile-4]

This script:
  1. Loads N selected strip PNGs for each dataset.
  2. Extracts the 4 most informative panels (Input, GT, Fixed, Best).
  3. Replaces near-black void pixels (ignore class) with white so colours are
     consistent between GT and predictions.
  4. Composes a SINGLE combined figure (ACDC on top, KITTI below) for the paper.

Usage (run locally on Mac — no GPU needed):
  python paper/compose_qualitative.py

Outputs:
  paper/figures/qualitative_combined_paper.pdf   (and .png)
  paper/figures/qualitative_acdc_paper.pdf       (and .png)   ← kept for supplement
  paper/figures/qualitative_kitti_paper.pdf      (and .png)   ← kept for supplement
"""
from __future__ import annotations

import glob
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib as mpl
import numpy as np
from PIL import Image

# ── Publication style (matches make_figures.py) ───────────────────────────────
mpl.rcParams.update({
    "font.family":        "sans-serif",
    "font.sans-serif":    ["Arial", "Helvetica", "DejaVu Sans"],
    "pdf.fonttype":       42,
    "ps.fonttype":        42,
    "font.size":          8,
    "axes.titlesize":     8,
    "savefig.dpi":        300,
    "savefig.bbox":       "tight",
    "savefig.pad_inches": 0.03,
})

FIGURES_DIR = os.path.join(os.path.dirname(__file__), "figures")

# Cityscapes 19-class palette — must match generate_qualitative.py PALETTE_19
CITYSCAPES_PALETTE: list[tuple[int, int, int]] = [
    (128, 64, 128),   # 0  road
    (244, 35, 232),   # 1  sidewalk
    (70,  70,  70),   # 2  building
    (102, 102, 156),  # 3  wall
    (190, 153, 153),  # 4  fence
    (153, 153, 153),  # 5  pole
    (250, 170,  30),  # 6  traffic light
    (220, 220,   0),  # 7  traffic sign
    (107, 142,  35),  # 8  vegetation
    (152, 251, 152),  # 9  terrain
    (70,  130, 180),  # 10 sky
    (220,  20,  60),  # 11 person
    (255,   0,   0),  # 12 rider
    (  0,   0, 142),  # 13 car
    (  0,   0,  70),  # 14 truck
    (  0,  60, 100),  # 15 bus
    (  0,  80, 100),  # 16 train
    (  0,   0, 230),  # 17 motorcycle
    (119,  11,  32),  # 18 bicycle
]

# Original strips have these columns (0-indexed) from generate_qualitative.py
STRIP_COLUMNS = {
    "Input RGB":        0,
    "Ground Truth":     1,
    "Fixed Camera":     2,
    "No Optics (Best)": 3,   # No Optics / Tile-2 ★
    "Tile-3":           4,
    "Tile-4":           5,
}

# Which panels to include in the paper figure, in order
PAPER_COLUMNS = [
    ("Input RGB",        "Input RGB"),
    ("Ground Truth",     "Ground Truth"),
    ("Fixed Camera",     "Fixed Camera"),
    ("No Optics (Best)", "No Optics (Ours)"),
]

N_STRIP_COLS = 6   # number of panels in each strip PNG


# ── Palette normalisation ─────────────────────────────────────────────────────

def _build_void_mask(img: np.ndarray, threshold: int = 22) -> np.ndarray:
    """Return boolean mask where all RGB channels are below threshold (void/ignore black)."""
    return (img[:, :, 0] < threshold) & (img[:, :, 1] < threshold) & (img[:, :, 2] < threshold)


def _remove_void_black(img: np.ndarray, replacement: tuple[int, int, int] = (255, 255, 255)) -> np.ndarray:
    """Replace near-black void pixels with a neutral background colour."""
    out = img.copy()
    mask = _build_void_mask(out)
    out[mask] = replacement
    return out


def _snap_to_palette(seg: np.ndarray) -> np.ndarray:
    """Snap every segmentation pixel to its nearest Cityscapes palette colour.

    This corrects any slight JPEG/PNG compression artefacts in the colour values
    so that GT and predictions use exactly the same hues.
    """
    palette = np.array(CITYSCAPES_PALETTE, dtype=np.float32)  # (19, 3)
    flat = seg.reshape(-1, 3).astype(np.float32)
    # L2 distance to each palette colour
    dists = np.sum((flat[:, None, :] - palette[None, :, :]) ** 2, axis=2)  # (N, 19)
    nearest = np.argmin(dists, axis=1)
    snapped = palette[nearest].astype(np.uint8).reshape(seg.shape)
    return snapped


def _normalise_seg_panel(panel: np.ndarray, snap: bool = True) -> np.ndarray:
    """Remove void blacks then optionally snap to official palette."""
    out = _remove_void_black(panel)
    if snap:
        out = _snap_to_palette(out)
    return out


# ── Strip loading ─────────────────────────────────────────────────────────────

def _load_strip_panels(path: str, col_indices: list[int],
                       title_crop_rows: int = 0,
                       is_seg_col: list[bool] | None = None) -> list[np.ndarray]:
    """Load a strip PNG and return the requested column panels as numpy arrays.

    Args:
        is_seg_col: bool list matching col_indices; True = segmentation panel
                    (applies palette normalisation), False = RGB image.
    """
    img = np.array(Image.open(path).convert("RGB"))

    if title_crop_rows > 0:
        img = img[title_crop_rows:, :, :]

    H, W = img.shape[:2]
    panel_w = W // N_STRIP_COLS
    panels = []
    for k, ci in enumerate(col_indices):
        x0 = ci * panel_w
        x1 = (ci + 1) * panel_w if ci < N_STRIP_COLS - 1 else W
        panel = img[:, x0:x1, :].copy()
        if is_seg_col and is_seg_col[k]:
            panel = _normalise_seg_panel(panel)
        panels.append(panel)
    return panels


def _estimate_title_crop(strip_path: str) -> int:
    """Estimate pixel height of the suptitle area (near-white rows at top)."""
    img = np.array(Image.open(strip_path).convert("RGB"))
    row_means = img.mean(axis=(1, 2))
    cutoff = 0
    for row_idx, mean in enumerate(row_means):
        if mean > 230:
            cutoff = row_idx + 1
        else:
            break
    return cutoff


# ── Single-dataset figure ─────────────────────────────────────────────────────

def compose_figure(
    strip_dir: str,
    out_stem: str,
    dataset_label: str,
    n_scenes: int = 3,
    scene_ranks: list[int] | None = None,
    col_specs: list[tuple[str, str]] = PAPER_COLUMNS,
    fig_w: float = 6.5,
) -> tuple[list[list[np.ndarray]], float]:
    """Build an N-scene × M-panel grid.

    Returns (all_rows, panel_aspect) so it can be reused in the combined figure.
    """
    pattern = os.path.join(strip_dir, "qual_*.png")
    strip_paths = sorted(glob.glob(pattern),
                         key=lambda p: int(p.split("rank")[1][:2]) if "rank" in p else 0)

    if not strip_paths:
        print(f"[warn] No strip PNGs found in {strip_dir}")
        return [], 0.5

    if scene_ranks is not None:
        selected_paths = []
        for rank in scene_ranks:
            matches = [p for p in strip_paths if f"rank{rank:02d}" in p]
            if matches:
                selected_paths.append(matches[0])
        strip_paths = selected_paths
    else:
        strip_paths = strip_paths[:n_scenes]

    if not strip_paths:
        print(f"[warn] Could not find requested strips in {strip_dir}")
        return [], 0.5

    col_indices = [STRIP_COLUMNS[k] for k, _ in col_specs]
    col_labels  = [lbl for _, lbl in col_specs]
    n_cols      = len(col_specs)

    # Which columns are segmentation panels (need palette normalisation)
    seg_keys    = {"Ground Truth", "Fixed Camera", "No Optics (Best)", "Tile-3", "Tile-4"}
    is_seg_col  = [(k in seg_keys) for k, _ in col_specs]

    title_crop = _estimate_title_crop(strip_paths[0])

    all_rows: list[list[np.ndarray]] = []
    for path in strip_paths:
        panels = _load_strip_panels(path, col_indices, title_crop_rows=title_crop,
                                    is_seg_col=is_seg_col)
        H = panels[0].shape[0]
        panel_title_crop = max(0, int(H * 0.07))
        panels = [p[panel_title_crop:, :, :] for p in panels]
        all_rows.append(panels)

    ph, pw = all_rows[0][0].shape[:2]
    aspect = ph / pw

    panel_w_in  = fig_w / n_cols
    panel_h_in  = panel_w_in * aspect
    header_h_in = 0.20

    fig_h = panel_h_in * len(all_rows) + header_h_in + 0.02
    fig   = plt.figure(figsize=(fig_w, fig_h), facecolor="white")

    gs = gridspec.GridSpec(
        len(all_rows) + 1, n_cols,
        figure=fig,
        height_ratios=[header_h_in / panel_h_in] + [1.0] * len(all_rows),
        hspace=0.008,
        wspace=0.006,
    )

    for j, lbl in enumerate(col_labels):
        ax = fig.add_subplot(gs[0, j])
        ax.text(0.5, 0.15, lbl, ha="center", va="bottom",
                fontsize=9, fontweight="bold",
                transform=ax.transAxes, color="#111111")
        ax.axis("off")

    for i, panels in enumerate(all_rows):
        for j, panel_img in enumerate(panels):
            ax = fig.add_subplot(gs[i + 1, j])
            ax.imshow(panel_img, interpolation="bilinear", aspect="auto")
            ax.axis("off")
            for spine in ax.spines.values():
                spine.set_visible(True)
                spine.set_color("white")
                spine.set_linewidth(0.8)
            if j == 0:
                ax.text(-0.03, 0.5, f"({i+1})",
                        ha="right", va="center", fontsize=8,
                        fontweight="bold", color="#555555",
                        transform=ax.transAxes)

    fig.suptitle(f"{dataset_label}  —  Qualitative Segmentation Comparison",
                 fontsize=9.5, fontweight="bold", y=1.002, color="#111111")

    out_pdf = os.path.join(FIGURES_DIR, f"{out_stem}.pdf")
    out_png = os.path.join(FIGURES_DIR, f"{out_stem}.png")
    fig.savefig(out_pdf, dpi=300)
    fig.savefig(out_png, dpi=200)
    plt.close(fig)
    print(f"Saved: {out_pdf}")
    print(f"Saved: {out_png}")

    return all_rows, aspect


# ── Combined figure (ACDC + KITTI in one grid) ────────────────────────────────

def compose_combined(
    acdc_strip_dir: str,
    kitti_strip_dir: str,
    out_stem: str = "qualitative_combined_paper",
    acdc_ranks: list[int] | None = None,
    kitti_ranks: list[int] | None = None,
    col_specs: list[tuple[str, str]] = PAPER_COLUMNS,
    fig_w: float = 7.0,
    n_acdc: int = 3,
    n_kitti: int = 2,
) -> None:
    """Single figure combining ACDC (top) and KITTI-360 (bottom) scenes.

    Layout:
      Column headers row
      [ACDC label | scene 1 panels]
      [ACDC label | scene 2 panels]
      [ACDC label | scene 3 panels]
      thin divider
      [KITTI label | scene 1 panels]
      [KITTI label | scene 2 panels]
    """
    col_indices = [STRIP_COLUMNS[k] for k, _ in col_specs]
    col_labels  = [lbl for _, lbl in col_specs]
    n_cols      = len(col_specs)
    seg_keys    = {"Ground Truth", "Fixed Camera", "No Optics (Best)", "Tile-3", "Tile-4"}
    is_seg_col  = [(k in seg_keys) for k, _ in col_specs]

    def _load_dataset(strip_dir, ranks, n_scenes):
        pattern = os.path.join(strip_dir, "qual_*.png")
        paths = sorted(glob.glob(pattern),
                       key=lambda p: int(p.split("rank")[1][:2]) if "rank" in p else 0)
        if not paths:
            return [], 0.5
        if ranks is not None:
            sel = []
            for r in ranks:
                m = [p for p in paths if f"rank{r:02d}" in p]
                if m:
                    sel.append(m[0])
            paths = sel
        else:
            paths = paths[:n_scenes]
        title_crop = _estimate_title_crop(paths[0]) if paths else 0
        rows = []
        for path in paths:
            panels = _load_strip_panels(path, col_indices, title_crop_rows=title_crop,
                                        is_seg_col=is_seg_col)
            H = panels[0].shape[0]
            crop = max(0, int(H * 0.07))
            panels = [p[crop:, :, :] for p in panels]
            rows.append(panels)
        # panel aspect from first loaded panel
        if rows:
            ph, pw = rows[0][0].shape[:2]
            return rows, ph / pw
        return [], 0.5

    acdc_rows,  acdc_aspect  = _load_dataset(acdc_strip_dir,  acdc_ranks,  n_acdc)
    kitti_rows, kitti_aspect = _load_dataset(kitti_strip_dir, kitti_ranks, n_kitti)

    if not acdc_rows and not kitti_rows:
        print("[warn] No data loaded for combined figure")
        return

    # Use the average aspect ratio
    aspect = (acdc_aspect + kitti_aspect) / 2 if acdc_rows and kitti_rows else acdc_aspect or kitti_aspect

    panel_w_in  = fig_w / n_cols
    panel_h_in  = panel_w_in * aspect
    header_h_in = 0.22    # column header strip
    divider_in  = 0.18    # thin gap between datasets
    ds_label_in = 0.22    # dataset section label

    n_a = len(acdc_rows)
    n_k = len(kitti_rows)
    total_rows = n_a + n_k

    # Height ratios: [header, ds_label, scene*n_a, divider, ds_label, scene*n_k]
    # Encode as gridspec rows
    hr_header   = header_h_in  / panel_h_in
    hr_ds_label = ds_label_in  / panel_h_in
    hr_divider  = divider_in   / panel_h_in

    height_ratios = (
        [hr_header, hr_ds_label]
        + [1.0] * n_a
        + ([hr_divider, hr_ds_label] if n_k else [])
        + [1.0] * n_k
    )
    n_gs_rows = len(height_ratios)

    fig_h = (panel_h_in * total_rows + header_h_in + ds_label_in * (2 if n_k else 1)
             + (divider_in if n_k else 0) + 0.05)

    fig = plt.figure(figsize=(fig_w, fig_h), facecolor="white")
    gs  = gridspec.GridSpec(
        n_gs_rows, n_cols,
        figure=fig,
        height_ratios=height_ratios,
        hspace=0.006,
        wspace=0.006,
    )

    # ── Column headers ────────────────────────────────────────────────────────
    for j, lbl in enumerate(col_labels):
        ax = fig.add_subplot(gs[0, j])
        ax.text(0.5, 0.1, lbl, ha="center", va="bottom",
                fontsize=9, fontweight="bold",
                transform=ax.transAxes, color="#111111")
        ax.axis("off")

    def _section_label(gs_row, label):
        ax = fig.add_subplot(gs[gs_row, :])
        ax.set_facecolor("#F0F4F8")
        ax.text(0.012, 0.5, label, ha="left", va="center",
                fontsize=8.5, fontweight="bold", color="#1A237E",
                transform=ax.transAxes)
        ax.axis("off")
        for spine in ax.spines.values():
            spine.set_visible(False)

    def _scene_rows(rows, gs_start, scene_offset=0):
        for i, panels in enumerate(rows):
            for j, panel_img in enumerate(panels):
                ax = fig.add_subplot(gs[gs_start + i, j])
                ax.imshow(panel_img, interpolation="bilinear", aspect="auto")
                ax.axis("off")
                for spine in ax.spines.values():
                    spine.set_visible(True)
                    spine.set_color("white")
                    spine.set_linewidth(0.8)
                if j == 0:
                    ax.text(-0.03, 0.5, f"({scene_offset + i + 1})",
                            ha="right", va="center", fontsize=8,
                            fontweight="bold", color="#555555",
                            transform=ax.transAxes)

    # ── ACDC section ─────────────────────────────────────────────────────────
    if acdc_rows:
        _section_label(1, "ACDC  (Adverse Conditions: fog, night, rain, snow)")
        _scene_rows(acdc_rows, gs_start=2, scene_offset=0)

    # ── KITTI section ─────────────────────────────────────────────────────────
    if kitti_rows:
        kitti_gs_start = 2 + n_a + 2   # header + ds_label + n_a scenes + divider + ds_label
        # divider row
        div_ax = fig.add_subplot(gs[2 + n_a, :])
        div_ax.axis("off")
        # section label
        _section_label(2 + n_a + 1, "KITTI-360  (Normal Conditions)")
        _scene_rows(kitti_rows, gs_start=kitti_gs_start, scene_offset=0)

    fig.suptitle("Qualitative Segmentation Comparison — Raw2Task",
                 fontsize=10, fontweight="bold", y=1.002, color="#111111")

    out_pdf = os.path.join(FIGURES_DIR, f"{out_stem}.pdf")
    out_png = os.path.join(FIGURES_DIR, f"{out_stem}.png")
    fig.savefig(out_pdf, dpi=300)
    fig.savefig(out_png, dpi=200)
    plt.close(fig)
    print(f"Saved: {out_pdf}")
    print(f"Saved: {out_png}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    os.makedirs(FIGURES_DIR, exist_ok=True)

    acdc_dir  = os.path.join(FIGURES_DIR, "qualitative_acdc")
    kitti_dir = os.path.join(FIGURES_DIR, "qualitative_kitti")

    # ── Per-dataset supplements ───────────────────────────────────────────────
    if os.path.isdir(acdc_dir):
        compose_figure(
            strip_dir=acdc_dir,
            out_stem="qualitative_acdc_paper",
            dataset_label="ACDC (Adverse Conditions)",
            scene_ranks=[1, 2, 3],
        )
    else:
        print(f"[skip] ACDC qualitative dir not found: {acdc_dir}")

    if os.path.isdir(kitti_dir):
        compose_figure(
            strip_dir=kitti_dir,
            out_stem="qualitative_kitti_paper",
            dataset_label="KITTI-360",
            scene_ranks=[1, 2, 3],
        )
    else:
        print(f"[skip] KITTI qualitative dir not found: {kitti_dir}")

    # ── Combined main-paper figure ────────────────────────────────────────────
    if os.path.isdir(acdc_dir) or os.path.isdir(kitti_dir):
        compose_combined(
            acdc_strip_dir=acdc_dir  if os.path.isdir(acdc_dir)  else "",
            kitti_strip_dir=kitti_dir if os.path.isdir(kitti_dir) else "",
            out_stem="qualitative_combined_paper",
            acdc_ranks=[1, 2, 3],
            kitti_ranks=[1, 2],
            n_acdc=3,
            n_kitti=2,
        )


if __name__ == "__main__":
    main()
