"""
Compose publication-quality qualitative figures from existing strip PNGs.

Each strip PNG (generated by generate_qualitative.py) contains 6 side-by-side panels:
  [Input RGB] [Ground Truth] [Fixed Camera] [No Optics (Tile-2)] [Tile-3] [Tile-4]

This script:
  1. Loads N selected strip PNGs for each dataset.
  2. Extracts the 4 most informative panels (Input, GT, Fixed, Best).
  3. Composes them into a portrait-oriented grid figure suitable for printing.

Usage (run locally on Mac — no GPU needed):
  python paper/compose_qualitative.py

Outputs:
  paper/figures/qualitative_acdc_paper.pdf   (and .png)
  paper/figures/qualitative_kitti_paper.pdf  (and .png)
"""
from __future__ import annotations

import glob
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib as mpl
import numpy as np
from PIL import Image

# ── Publication style (matches make_figures.py) ───────────────────────────────
mpl.rcParams.update({
    "font.family":        "sans-serif",
    "font.sans-serif":    ["Arial", "Helvetica", "DejaVu Sans"],
    "pdf.fonttype":       42,
    "ps.fonttype":        42,
    "font.size":          8,
    "axes.titlesize":     8,
    "savefig.dpi":        300,
    "savefig.bbox":       "tight",
    "savefig.pad_inches": 0.03,
})

FIGURES_DIR = os.path.join(os.path.dirname(__file__), "figures")

# Original strips have these columns (0-indexed) from generate_qualitative.py
STRIP_COLUMNS = {
    "Input RGB":           0,
    "Ground Truth":        1,
    "Fixed Camera":        2,
    "No Optics (Best)":    3,   # No Optics / Tile-2 ★
    "Tile-3":              4,
    "Tile-4":              5,
}

# Which panels to include in the paper figure, in order
PAPER_COLUMNS = [
    ("Input RGB",       "Input RGB"),
    ("Ground Truth",    "Ground Truth"),
    ("Fixed Camera",    "Fixed Camera"),
    ("No Optics (Best)", "No Optics (Ours, T=2)$^\\star$"),
]

N_STRIP_COLS = 6   # number of panels in each strip PNG


def _load_strip_panels(path: str, col_indices: list[int],
                        title_crop_rows: int = 0) -> list[np.ndarray]:
    """Load a strip PNG and return the requested column panels as numpy arrays."""
    img = np.array(Image.open(path).convert("RGB"))

    # Strip the suptitle region from the top if present
    if title_crop_rows > 0:
        img = img[title_crop_rows:, :, :]

    H, W = img.shape[:2]
    panel_w = W // N_STRIP_COLS
    panels = []
    for ci in col_indices:
        x0 = ci * panel_w
        x1 = (ci + 1) * panel_w if ci < N_STRIP_COLS - 1 else W
        panel = img[:, x0:x1, :]
        panels.append(panel)
    return panels


def _estimate_title_crop(strip_path: str) -> int:
    """Estimate the pixel height of the suptitle area by looking for a
    near-white row band at the top of the image."""
    img = np.array(Image.open(strip_path).convert("RGB"))
    # Row is "title area" if its mean brightness > 235 (near-white background)
    row_means = img.mean(axis=(1, 2))
    cutoff = 0
    for row_idx, mean in enumerate(row_means):
        if mean > 230:
            cutoff = row_idx + 1
        else:
            break
    return cutoff


def compose_figure(
    strip_dir: str,
    out_stem: str,
    dataset_label: str,
    n_scenes: int = 3,
    scene_ranks: list[int] | None = None,
    col_specs: list[tuple[str, str]] = PAPER_COLUMNS,
) -> None:
    """Build a N-scene × M-panel grid from the specified strip directory.

    Args:
        strip_dir:     Directory containing qual_*.png strips.
        out_stem:      Output file stem (without extension).
        dataset_label: Display name for the dataset (e.g. "ACDC").
        n_scenes:      Number of scenes to include (if scene_ranks is None).
        scene_ranks:   Override: specific 1-indexed strip ranks to use.
        col_specs:     List of (strip_col_key, display_label) pairs.
    """
    # Find strip files, sorted by rank number
    pattern = os.path.join(strip_dir, "qual_*.png")
    strip_paths = sorted(glob.glob(pattern),
                         key=lambda p: int(p.split("rank")[1][:2]) if "rank" in p else 0)

    if not strip_paths:
        print(f"[warn] No strip PNGs found in {strip_dir}")
        return

    if scene_ranks is not None:
        selected_paths = []
        for rank in scene_ranks:
            matches = [p for p in strip_paths if f"rank{rank:02d}" in p]
            if matches:
                selected_paths.append(matches[0])
        strip_paths = selected_paths
    else:
        strip_paths = strip_paths[:n_scenes]

    if not strip_paths:
        print(f"[warn] Could not find requested strips in {strip_dir}")
        return

    col_indices  = [STRIP_COLUMNS[k] for k, _ in col_specs]
    col_labels   = [lbl for _, lbl in col_specs]
    n_rows = len(strip_paths)
    n_cols = len(col_specs)

    # Estimate title crop from first strip
    title_crop = _estimate_title_crop(strip_paths[0])

    # Load all panels
    all_rows: list[list[np.ndarray]] = []
    for path in strip_paths:
        panels = _load_strip_panels(path, col_indices, title_crop_rows=title_crop)
        # Crop per-panel axis title area (usually ~35–55 px at the very top of each panel)
        H = panels[0].shape[0]
        panel_title_crop = max(0, int(H * 0.07))  # top 7% is usually axis title text
        panels = [p[panel_title_crop:, :, :] for p in panels]
        all_rows.append(panels)

    # Determine panel aspect ratio from first panel
    ph, pw = all_rows[0][0].shape[:2]
    aspect = ph / pw  # height / width

    # Figure sizing — 6.5 in wide (double-column CVPR width)
    fig_w       = 6.5
    panel_w_in  = fig_w / n_cols
    panel_h_in  = panel_w_in * aspect
    header_h_in = 0.20   # compact bold header strip

    fig_h = panel_h_in * n_rows + header_h_in + 0.02
    fig   = plt.figure(figsize=(fig_w, fig_h), facecolor="white")

    gs = gridspec.GridSpec(
        n_rows + 1, n_cols,
        figure=fig,
        height_ratios=[header_h_in / panel_h_in] + [1.0] * n_rows,
        hspace=0.008,   # near-zero gap — tight grid
        wspace=0.006,
    )

    # Column header row — no background, just bold text
    for j, (_, lbl) in enumerate(col_specs):
        ax = fig.add_subplot(gs[0, j])
        ax.text(0.5, 0.15, lbl,
                ha="center", va="bottom",
                fontsize=9, fontweight="bold",
                transform=ax.transAxes, color="#111111")
        ax.axis("off")

    # Image rows — no borders, pure image grid
    for i, panels in enumerate(all_rows):
        for j, panel_img in enumerate(panels):
            ax = fig.add_subplot(gs[i + 1, j])
            ax.imshow(panel_img, interpolation="bilinear", aspect="auto")
            ax.axis("off")
            # Thin white border to separate panels visually
            for spine in ax.spines.values():
                spine.set_visible(True)
                spine.set_color("white")
                spine.set_linewidth(0.8)
            # Left-side (i+1) scene index
            if j == 0:
                ax.text(-0.03, 0.5, f"({i+1})",
                        ha="right", va="center", fontsize=8,
                        fontweight="bold", color="#555555",
                        transform=ax.transAxes)

    fig.suptitle(f"{dataset_label}  —  Qualitative Segmentation Comparison",
                 fontsize=9.5, fontweight="bold", y=1.002, color="#111111")

    out_pdf = os.path.join(FIGURES_DIR, f"{out_stem}.pdf")
    out_png = os.path.join(FIGURES_DIR, f"{out_stem}.png")
    fig.savefig(out_pdf, dpi=300)
    fig.savefig(out_png, dpi=200)
    plt.close(fig)
    print(f"Saved: {out_pdf}")
    print(f"Saved: {out_png}")


def main():
    os.makedirs(FIGURES_DIR, exist_ok=True)

    # ACDC: show top-3 scenes (rank 1=fog, rank 2=night, rank 3=rain)
    acdc_dir = os.path.join(FIGURES_DIR, "qualitative_acdc")
    if os.path.isdir(acdc_dir):
        compose_figure(
            strip_dir=acdc_dir,
            out_stem="qualitative_acdc_paper",
            dataset_label="ACDC (Adverse Conditions)",
            scene_ranks=[1, 2, 3],
        )
    else:
        print(f"[skip] ACDC qualitative dir not found: {acdc_dir}")

    # KITTI-360: show top-2 most informative scenes
    kitti_dir = os.path.join(FIGURES_DIR, "qualitative_kitti")
    if os.path.isdir(kitti_dir):
        compose_figure(
            strip_dir=kitti_dir,
            out_stem="qualitative_kitti_paper",
            dataset_label="KITTI-360",
            scene_ranks=[1, 2, 3],
        )
    else:
        print(f"[skip] KITTI qualitative dir not found: {kitti_dir}")


if __name__ == "__main__":
    main()
